module.exports = {
  indexBanner: "/banner/list?type=app",
  banner: "/banner/list?type=index",
  nav: '/shop/goods/category/all',
  goods: '/shop/goods/list',
  srcoll: '/notice/list',
  classify: '/shop/goods/category/all',
  detail: '/shop/goods/detail',
  register: '/user/wxapp/register/complex',
  login: '/user/wxapp/login',
  Info: '/user/detail',
  add: '/shopping-cart/add',
  carList: '/shopping-cart/info',
  removeCar: '/shopping-cart/remove',
  carChange: '/shopping-cart/modifyNumber',
  address: '/user/shipping-address/default/v2',
  add_address: '/user/shipping-address/add',
  address_list: '/user/shipping-address/list',
  remove_address: '/user/shipping-address/delete',
  news: '/notice/detail',
}